# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 538b672b86354bca59023965abab2cb2cc0f331e031543c0c00823f06949573f36541db78ef3e5df852d4f7b878e299e573255e19c54365802e48b0e057fefa0
  

test:
  secret_key_base: 12a857c808371151e0ad3cfaf4fcf4f9e339d116c983f61e52eea7e95351907aae58f16a8e2736d26e54ae5895dd9e3b2a5596c9d723b3d4e6433decdca068ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  
